scenario: scenarios.nav_demo

agent:
  behavior_tree_xml: "default_bt.xml"
  namespaces: []

bt_runner:
  # ▼ 이 줄을 추가하세요!
  profiling_mode: false
  
  bt_tick_rate: 30
  bt_visualiser:
    enabled: true
    screen_width: 800
    screen_height: 600
    direction: "Vertical"